"""media_files url unique

Revision ID: d7f7ce457a08
Revises: 04cbaa45201d
Create Date: 2026-08-29 01:06:06.737713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f7ce457a08'
down_revision: Union[str, Sequence[str], None] = '04cbaa45201d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'media_files', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_files', type_='unique')
    # ### end Alembic commands ###
