"""add user_id to media_files

Revision ID: 530c1f7299f3
Revises: 8936081c845a
Create Date: 2026-09-06 21:21:41.877426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530c1f7299f3'
down_revision: Union[str, Sequence[str], None] = '8936081c845a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'media_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_files', type_='foreignkey')
    op.drop_column('media_files', 'user_id')
    # ### end Alembic commands ###
